/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const BlockWorld = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('3d-models-contamination/blockworld-plus.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="terrain_plane_water001"
          geometry={nodes.terrain_plane_water001.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-85.022, 0, -20.32]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.02, 0.01]}
        />
        <group
          name="terrain_plane_slope2001"
          position={[4.956, 0, -34.902]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          receiveShadow
        >
          <mesh
            name="Scene019"
            geometry={nodes.Scene019.geometry}
            material={materials['atlas_LPUP.006']}
            receiveShadow
          />
          <mesh
            name="Scene019_1"
            geometry={nodes.Scene019_1.geometry}
            material={materials.atlas_LPUP}
            receiveShadow
          />
          <mesh
            name="Scene019_2"
            geometry={nodes.Scene019_2.geometry}
            material={materials['atlas_LPUP.001']}
            receiveShadow
          />
          <mesh
            name="Scene019_3"
            geometry={nodes.Scene019_3.geometry}
            material={materials['atlas_LPUP.003']}
            receiveShadow
          />
          <mesh
            name="Scene019_4"
            geometry={nodes.Scene019_4.geometry}
            material={materials['atlas_LPUP.010']}
            receiveShadow
          />
          <mesh
            name="Scene019_5"
            geometry={nodes.Scene019_5.geometry}
            material={materials['atlas_LPUP.011']}
            receiveShadow
          />
          <mesh
            name="Scene019_6"
            geometry={nodes.Scene019_6.geometry}
            material={materials['atlas_LPUP.004']}
            receiveShadow
          />
          <mesh
            name="Scene019_7"
            geometry={nodes.Scene019_7.geometry}
            material={materials['atlas_LPUP.002']}
            receiveShadow
          />
          <mesh
            name="Scene019_8"
            geometry={nodes.Scene019_8.geometry}
            material={materials['atlas_LPUP.005']}
            receiveShadow
          />
        </group>

        <mesh
          name="terrain_plane_water005"
          geometry={nodes.terrain_plane_water005.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-85.022, 0, 54.971]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water006"
          geometry={nodes.terrain_plane_water006.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-55.054, 0, 54.971]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water007"
          geometry={nodes.terrain_plane_water007.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-25.042, 0, 54.971]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water008"
          geometry={nodes.terrain_plane_water008.geometry}
          material={materials['atlas_LPUP.012']}
          position={[4.956, 0, 54.971]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="tile_water"
          geometry={nodes.tile_water.geometry}
          material={materials['atlas_LPUP.007']}
          position={[-40.15, -2.899, 69.92]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.04, 0.002, 0.01]}
        />
        <mesh
          name="tile_water001"
          geometry={nodes.tile_water001.geometry}
          material={materials['atlas_LPUP.007']}
          position={[19.757, -2.899, 54.99]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.01, 0.002, 0.01]}
        />
        <mesh
          name="tile_water002"
          geometry={nodes.tile_water002.geometry}
          material={materials['atlas_LPUP.007']}
          position={[-100.263, -2.933, -20.305]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.02, 0.002, 0.01]}
        />
        <mesh
          name="tile_plain_dirt"
          geometry={nodes.tile_plain_dirt.geometry}
          material={materials['atlas_LPUP.008']}
          position={[4.737, 0.09, 24.97]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt001"
          geometry={nodes.tile_plain_dirt001.geometry}
          material={materials['atlas_LPUP.008']}
          position={[4.777, 0.09, 54.97]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt002"
          geometry={nodes.tile_plain_dirt002.geometry}
          material={materials['atlas_LPUP.008']}
          position={[4.737, 0.09, -5.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt003"
          geometry={nodes.tile_plain_dirt003.geometry}
          material={materials['atlas_LPUP.008']}
          position={[4.737, 6.09, -35.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.02]}
        />
        <mesh
          name="tile_plain_dirt004"
          geometry={nodes.tile_plain_dirt004.geometry}
          material={materials['atlas_LPUP.008']}
          position={[4.737, 6.09, -34.88]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.02]}
        />
        <mesh
          name="tile_plain_dirt005"
          geometry={nodes.tile_plain_dirt005.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-25.263, 6.09, -34.88]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.02]}
        />
        <mesh
          name="tile_plain_dirt006"
          geometry={nodes.tile_plain_dirt006.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-55.263, 6.09, -34.88]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.02]}
        />
        <mesh
          name="tile_plain_dirt007"
          geometry={nodes.tile_plain_dirt007.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.263, 0.09, -34.88]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt008"
          geometry={nodes.tile_plain_dirt008.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.103, 0.09, -34.85]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt009"
          geometry={nodes.tile_plain_dirt009.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.103, 0.09, -4.85]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt010"
          geometry={nodes.tile_plain_dirt010.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.103, 0.09, 25.15]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt011"
          geometry={nodes.tile_plain_dirt011.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.103, 0.09, 55.15]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          name="tile_plain_dirt012"
          geometry={nodes.tile_plain_dirt012.geometry}
          material={materials['atlas_LPUP.008']}
          position={[-85.103, 0.09, 54.96]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="building_cabin_small"
          geometry={nodes.building_cabin_small.geometry}
          material={materials['atlas_LPUP.009']}
          position={[5.1, 0, 22.22]}
          rotation={[Math.PI / 2, 0, 0.925]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="building_cabin_small001"
          geometry={nodes.building_cabin_small001.geometry}
          material={materials['atlas_LPUP.009']}
          position={[-14.869, 0, 22.289]}
          rotation={[Math.PI / 2, 0, -0.838]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="industry_factory_old"
          geometry={nodes.industry_factory_old.geometry}
          material={materials['atlas_LPUP.013']}
          position={[-4, 5.99, -45.31]}
          rotation={[Math.PI / 2, 0, 1.588]}
          scale={0.005}

          castShadow
        />
        <mesh
          name="lighthouse"
          geometry={nodes.lighthouse.geometry}
          material={materials['atlas_LPUP.014']}
          position={[-94.153, 0, 23.241]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <group
          name="tractor"
          position={[-2.258, 0, 16.199]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water003"
          geometry={nodes.terrain_plane_water003.geometry}
          material={materials['atlas_LPUP.012']}
          position={[4.956, 0, 24.977]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water004"
          geometry={nodes.terrain_plane_water004.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-19.066, 0, -10.952]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water009"
          geometry={nodes.terrain_plane_water009.geometry}
          material={materials['atlas_LPUP.012']}
          position={[11.001, 0, 7.077]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water010"
          geometry={nodes.terrain_plane_water010.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-55.008, 0, -28.912]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water011"
          geometry={nodes.terrain_plane_water011.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-67.084, 0, -22.882]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water012"
          geometry={nodes.terrain_plane_water012.geometry}
          material={materials['atlas_LPUP.012']}
          position={[5.097, 0, -16.987]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water013"
          geometry={nodes.terrain_plane_water013.geometry}
          material={materials['atlas_LPUP.012']}
          position={[4.956, 0, 12.842]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water014"
          geometry={nodes.terrain_plane_water014.geometry}
          material={materials['atlas_LPUP.012']}
          position={[5.116, 0, -34.438]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water015"
          geometry={nodes.terrain_plane_water015.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-30.953, 0, -22.925]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={-0.01}
        />
        <mesh
          name="terrain_plane_water016"
          geometry={nodes.terrain_plane_water016.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-6.954, 0, -28.885]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water017"
          geometry={nodes.terrain_plane_water017.geometry}
          material={materials['atlas_LPUP.012']}
          position={[5.097, 0, -16.704]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="terrain_plane_water018"
          geometry={nodes.terrain_plane_water018.geometry}
          material={materials['atlas_LPUP.012']}
          position={[-13.348, 0, -35]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="tree"
          geometry={nodes.tree.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-44.376, 3.57, 17.672]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree001"
          geometry={nodes.tree001.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-38.583, 4.93, 13.843]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree002"
          geometry={nodes.tree002.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-30.729, 3.9, 9.818]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree003"
          geometry={nodes.tree003.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-32.398, 3.04, 1.964]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree004"
          geometry={nodes.tree004.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-52.132, 2.96, 13.057]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree005"
          geometry={nodes.tree005.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-46.339, 4.81, 9.229]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree006"
          geometry={nodes.tree006.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-38.485, 4.51, 5.203]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree007"
          geometry={nodes.tree007.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-40.154, 2.42, -2.651]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree008"
          geometry={nodes.tree008.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-53.506, 1.89, 0.098]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree009"
          geometry={nodes.tree009.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-46.928, 3.86, 2.945]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree010"
          geometry={nodes.tree010.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-46.339, 0.97, -7.265]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree011"
          geometry={nodes.tree011.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-36.914, 0, -8.149]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree012"
          geometry={nodes.tree012.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-13.445, 5.35, -47.465]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree013"
          geometry={nodes.tree013.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-33.178, 3.63, -36.372]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree014"
          geometry={nodes.tree014.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-27.386, 4.81, -40.2]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree015"
          geometry={nodes.tree015.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-19.532, 5.22, -44.226]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree016"
          geometry={nodes.tree016.geometry}
          material={materials['atlas_LPUP.016']}
          position={[-34.553, 5.58, -49.331]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall"
          geometry={nodes.tree_tall.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-5.02, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall001"
          geometry={nodes.tree_tall001.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-3.196, 0, 2.209]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall002"
          geometry={nodes.tree_tall002.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-5.76, 0, -0.75]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall003"
          geometry={nodes.tree_tall003.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-33.773, 4.36, 7.141]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree_tall004"
          geometry={nodes.tree_tall004.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-38.113, 4.77, 8.088]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall005"
          geometry={nodes.tree_tall005.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-41.309, 0, 10.298]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall006"
          geometry={nodes.tree_tall006.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-43.874, 4.63, 7.339]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall007"
          geometry={nodes.tree_tall007.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-36.18, 2.32, -3.511]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall008"
          geometry={nodes.tree_tall008.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-37.916, 3.87, 0.75]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall009"
          geometry={nodes.tree_tall009.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-51.41, 3.35, 7.141]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall010"
          geometry={nodes.tree_tall010.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-45.846, 2.94, -2.249]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b"
          geometry={nodes.tree_torn_b.geometry}
          material={materials['atlas_LPUP.018']}
          position={[0.491, 0, 15.119]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b001"
          geometry={nodes.tree_torn_b001.geometry}
          material={materials['atlas_LPUP.018']}
          position={[10.21, 0, 11.781]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b002"
          geometry={nodes.tree_torn_b002.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-12.272, 0, -9.621]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree_torn_b003"
          geometry={nodes.tree_torn_b003.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-36.62, 0, -22.973]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b004"
          geometry={nodes.tree_torn_b004.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-60.869, 0, -19.537]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b005"
          geometry={nodes.tree_torn_b005.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-64.305, 0, -7.265]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b006"
          geometry={nodes.tree_torn_b006.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-70.687, 0, 9.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b007"
          geometry={nodes.tree_torn_b007.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-48.99, 2.18, -2.651]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b008"
          geometry={nodes.tree_torn_b008.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-54.095, 2.11, 5.4]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b009"
          geometry={nodes.tree_torn_b009.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-43.001, 4.71, 12.763]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b010"
          geometry={nodes.tree_torn_b010.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-37.307, 4.45, 17.966]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b011"
          geometry={nodes.tree_torn_b011.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-30.435, 3.83, 16.199]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b012"
          geometry={nodes.tree_torn_b012.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-41.43, 0, 2.16]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b013"
          geometry={nodes.tree_torn_b013.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-28.373, 2.99, 6.578]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_torn_b014"
          geometry={nodes.tree_torn_b014.geometry}
          material={materials['atlas_LPUP.018']}
          position={[-26.311, 1.12, -0.295]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall011"
          geometry={nodes.tree_tall011.geometry}
          material={materials['atlas_LPUP.017']}
          position={[9.493, 0, 8.97]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall012"
          geometry={nodes.tree_tall012.geometry}
          material={materials['atlas_LPUP.017']}
          position={[5.061, 0, 13.516]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall013"
          geometry={nodes.tree_tall013.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-1.757, 0, 12.095]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall014"
          geometry={nodes.tree_tall014.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-12.893, 0, -6.313]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}

          castShadow
        />
        <mesh
          name="tree_tall015"
          geometry={nodes.tree_tall015.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-64.31, 0, -3.642]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="tree_tall016"
          geometry={nodes.tree_tall016.geometry}
          material={materials['atlas_LPUP.017']}
          position={[-70.105, 0, 6.243]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="woman_ginger"
          geometry={nodes.woman_ginger.geometry}
          material={materials['atlas_LPUP.019']}
          position={[-13.408, 0.46, 27.442]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="man_guy"
          geometry={nodes.man_guy.geometry}
          material={materials['atlas_LPUP.020']}
          position={[0, 0.14, 26.826]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <group
          name="tractor001"
          position={[11.6, 0, 19.491]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          >
          <mesh
            name="tractor_base"
            geometry={nodes.tractor_base.geometry}
            material={materials['atlas_LPUP.021']}
            castShadow
          />
          <mesh
            name="tractor_wheel"
            geometry={nodes.tractor_wheel.geometry}
            material={materials['atlas_LPUP.021']}
            position={[-53.213, 99.633, -39.168]}
            castShadow
          />
          <mesh
            name="tractor_wheel_BL"
            geometry={nodes.tractor_wheel_BL.geometry}
            material={materials['atlas_LPUP.021']}
            position={[60.104, -100.626, -68.442]}

            castShadow
          />
          <mesh
            name="tractor_wheel_BR"
            geometry={nodes.tractor_wheel_BR.geometry}
            material={materials['atlas_LPUP.021']}
            position={[-60.104, -100.626, -68.442]}
            castShadow
          />
          <mesh
            name="tractor_wheel_FL"
            geometry={nodes.tractor_wheel_FL.geometry}
            material={materials['atlas_LPUP.021']}
            position={[53.214, 99.633, -39.168]}
            castShadow
          />
        </group>
        <mesh
          name="barrel_empty"
          geometry={nodes.barrel_empty.geometry}
          material={materials['atlas_LPUP.022']}
          position={[-5.185, -2.817, 56.968]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="barrel_old"
          geometry={nodes.barrel_old.geometry}
          material={materials['atlas_LPUP.023']}
          position={[1.377, -3.109, 59.849]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group
          name="bin_wheelie"
          position={[3.698, 0.079, 27.042]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <mesh
            name="bin_wheelie_base"
            geometry={nodes.bin_wheelie_base.geometry}
            material={materials['atlas_LPUP.024']}
          />
          <mesh
            name="bin_wheelie_top"
            geometry={nodes.bin_wheelie_top.geometry}
            material={materials['atlas_LPUP.024']}
            position={[-40, 0, -99.509]}
          />
        </group>
        <mesh
          name="body_bag"
          geometry={nodes.body_bag.geometry}
          material={materials['atlas_LPUP.025']}
          position={[-12.509, -2.522, 55.708]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="bridge_medieval_stone"
          geometry={nodes.bridge_medieval_stone.geometry}
          material={materials['atlas_LPUP.026']}
          position={[-7.091, -1.821, 18.749]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="bridge_medieval_stone001"
          geometry={nodes.bridge_medieval_stone001.geometry}
          material={materials['atlas_LPUP.026']}
          position={[-63.049, -1.764, -28.159]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.01}
        />
        <group name="chest" scale={0}>
          <mesh
            name="chest_base"
            geometry={nodes.chest_base.geometry}
            material={materials['atlas_LPUP.027']}
            scale={0}
          />
          <mesh
            name="chest_top"
            geometry={nodes.chest_top.geometry}
            material={materials['atlas_LPUP.027']}
            scale={0}
          />
        </group>
        <mesh
          name="coral_big_yellow"
          geometry={nodes.coral_big_yellow.geometry}
          material={materials['atlas_LPUP.028']}
          position={[-31.151, -4.657, 62.81]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="coral_small_blue"
          geometry={nodes.coral_small_blue.geometry}
          material={materials['atlas_LPUP.029']}
          position={[-28.471, -4.222, 62.833]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="coral_small_orange"
          geometry={nodes.coral_small_orange.geometry}
          material={materials['atlas_LPUP.030']}
          position={[-26.753, -4.172, 58.415]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="coral_small_red"
          geometry={nodes.coral_small_red.geometry}
          material={materials['atlas_LPUP.031']}
          position={[-35.339, -3.567, 60.872]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group
          name="fish"
          position={[-10.303, -2.548, 60.837]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <mesh
            name="Scene107"
            geometry={nodes.Scene107.geometry}
            material={materials._28_ORANGE_LPUP}
          />
          <mesh
            name="Scene107_1"
            geometry={nodes.Scene107_1.geometry}
            material={materials._17_GREY_DARKEST_LPUP}
          />
        </group>
        <mesh
          name="fish_swarm"
          geometry={nodes.fish_swarm.geometry}
          material={materials['atlas_LPUP.032']}
          position={[-14.562, -3.562, 64.568]}
          rotation={[Math.PI / 2, 0, 0.908]}
          scale={0.01}
        />
        <mesh
          name="garbage_bag"
          geometry={nodes.garbage_bag.geometry}
          material={materials['atlas_LPUP.033']}
          position={[2.784, 0, 28.578]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="garbage_open_a"
          geometry={nodes.garbage_open_a.geometry}
          material={materials['atlas_LPUP.034']}
          position={[5.568, 0.45, 32.612]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="garbage_open_b"
          geometry={nodes.garbage_open_b.geometry}
          material={materials['atlas_LPUP.035']}
          position={[4.432, 0.34, 30.964]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="garbage_pile"
          geometry={nodes.garbage_pile.geometry}
          material={materials['atlas_LPUP.036']}
          position={[2.216, 0.32, 31.532]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="grass_basic"
          geometry={nodes.grass_basic.geometry}
          material={materials['atlas_LPUP.037']}
          position={[5.137, 0.109, 28.356]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="grass_sea"
          geometry={nodes.grass_sea.geometry}
          material={materials['atlas_LPUP.038']}
          position={[-54.969, -2.462, 58.283]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="grass_sea_long"
          geometry={nodes.grass_sea_long.geometry}
          material={materials['atlas_LPUP.039']}
          position={[6.394, -1.369, 51.115]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="grass_tall"
          geometry={nodes.grass_tall.geometry}
          material={materials['atlas_LPUP.040']}
          position={[6.25, 0, 26.078]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="rock_pillar"
          geometry={nodes.rock_pillar.geometry}
          material={materials['atlas_LPUP.041']}
          position={[-50.791, -5.207, 61.366]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="rock_sharp"
          geometry={nodes.rock_sharp.geometry}
          material={materials['atlas_LPUP.042']}
          position={[-34.689, 0, 35.998]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        />
        <mesh
          name="seagull"
          geometry={nodes.seagull.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-88.754, 11.955, 15.138]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull001"
          geometry={nodes.seagull001.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-85.481, 11.955, 22.979]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull002"
          geometry={nodes.seagull002.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-88.754, 11.955, 26.592]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull003"
          geometry={nodes.seagull003.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-85.481, 11.955, 34.433]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull004"
          geometry={nodes.seagull004.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-83.163, 11.955, 14.457]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull005"
          geometry={nodes.seagull005.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-79.891, 11.955, 22.297]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull006"
          geometry={nodes.seagull006.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-83.163, 11.955, 25.91]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="seagull007"
          geometry={nodes.seagull007.geometry}
          material={materials['atlas_LPUP.043']}
          position={[-79.891, 11.955, 33.751]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="shark"
          geometry={nodes.shark.geometry}
          material={materials['atlas_LPUP.044']}
          position={[-68.233, -2.651, 59.299]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group name="trash_can" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh
          name="tires"
          geometry={nodes.tires.geometry}
          material={materials['atlas_LPUP.046']}
          position={[8.931, 0, 24.953]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="starfish"
          geometry={nodes.starfish.geometry}
          material={materials['atlas_LPUP.047']}
          position={[-0.758, -0.222, 43.558]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

export default BlockWorld;
useGLTF.preload('3d-models-contamination/blockworld-plus.glb')