/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const QuizBlockWorld = (props) => {

  const { nodes, materials } = useGLTF('/3d-models-quiz/quiz.glb')
  return (
    <group rotation={[Math.PI / 2, Math.PI / 2, -Math.PI / 2]} {...props} dispose={null}>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_water.geometry}
        material={materials['atlas_LPUP.002']}
        position={[-2.33, -0.21, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.013, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_water001.geometry}
        material={materials['atlas_LPUP.002']}
        position={[-0.453, -1.36, 19.672]}
        scale={[0.02, 0.021, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_water002.geometry}
        material={materials['atlas_LPUP.002']}
        position={[-0.576, -1.371, -19.398]}
        scale={[0.02, 0.021, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground_cracked_dirt.geometry}
        material={materials['atlas_LPUP.003']}
        position={[9.69, -0.18, -8.47]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_plain_dirt.geometry}
        material={materials['atlas_LPUP.004']}
        position={[12.87, 0.05, -12.18]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground_cracked_dirt001.geometry}
        material={materials['atlas_LPUP.003']}
        position={[9.676, -0.19, -14.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground_cracked_dirt002.geometry}
        material={materials['atlas_LPUP.003']}
        position={[15.614, -0.15, -8.426]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground_cracked_dirt003.geometry}
        material={materials['atlas_LPUP.003']}
        position={[15.614, -0.15, -14.218]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round.geometry}
        material={materials['atlas_LPUP.005']}
        position={[17.76, 0, -18.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round001.geometry}
        material={materials['atlas_LPUP.005']}
        position={[18.067, -0.72, -16.264]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_flat.geometry}
        material={materials['atlas_LPUP.006']}
        position={[6.75, 0, -17.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round002.geometry}
        material={materials['atlas_LPUP.005']}
        position={[7.668, -0.72, -18.397]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_dead_broken.geometry}
        material={materials['atlas_LPUP.007']}
        position={[19.09, 0, -5.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_flat001.geometry}
        material={materials['atlas_LPUP.006']}
        position={[19.08, 0, -14.004]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_dead_torn_a.geometry}
        material={materials['atlas_LPUP.008']}
        position={[9.91, 0, -18.27]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_bare.geometry}
        material={materials['atlas_LPUP.009']}
        position={[13.8, 0, -18.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cactus_medium.geometry}
        material={materials['atlas_LPUP.010']}
        position={[13.04, 0, -5.55]}
        rotation={[Math.PI / 2, 0, 1.187]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cactus_basic.geometry}
        material={materials['atlas_LPUP.011']}
        position={[13.88, 0, -5.69]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skull_human.geometry}
        material={materials['atlas_LPUP.012']}
        position={[6.46, 0.59, -16.94]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.5, 0.22, -10.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone001.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.602, 0.22, -10.786]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone002.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.283, 0.22, -10.815]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone003.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.27, 0.22, -11.051]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone004.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.624, 0.22, -11.128]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone005.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.873, 0.22, -10.92]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fish_bone007.geometry}
        material={materials['atlas_LPUP.013']}
        position={[11.937, 0.14, -10.7]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skull_human001.geometry}
        material={materials['atlas_LPUP.012']}
        position={[11.757, 0.14, -11.492]}
        rotation={[1.131, -0.26, 0.5]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_plain_grass.geometry}
        material={materials.atlas_LPUP}
        position={[12.38, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.005, 0.013, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_water003.geometry}
        material={materials['atlas_LPUP.002']}
        position={[-12.319, -1.354, -0.051]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.033, 0.023, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.building_cabin_small.geometry}
        material={materials['atlas_LPUP.014']}
        position={[15.86, 0, 16]}
        rotation={[Math.PI / 2, 0, 2.164]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_poplar.geometry}
        material={materials['atlas_LPUP.016']}
        position={[15.7, 0, 10.71]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_poplar001.geometry}
        material={materials['atlas_LPUP.016']}
        position={[10.566, 0, 17.437]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_poplar002.geometry}
        material={materials['atlas_LPUP.016']}
        position={[14.52, 0, 6.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_poplar003.geometry}
        material={materials['atlas_LPUP.016']}
        position={[6.73, 0, 18.027]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group position={[10.4, 0, 14.51]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trash_can_base.geometry}
          material={materials['atlas_LPUP.017']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trash_can_lid.geometry}
          material={materials['atlas_LPUP.017']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm_big.geometry}
        material={materials['atlas_LPUP.018']}
        position={[6.59, 0, -2.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm_big001.geometry}
        material={materials['atlas_LPUP.018']}
        position={[11.542, 0, -0.95]}
        rotation={[Math.PI / 2, 0, -1.728]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm_big002.geometry}
        material={materials['atlas_LPUP.018']}
        position={[16.465, 0, -2.658]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm_big003.geometry}
        material={materials['atlas_LPUP.018']}
        position={[16.949, 0, 1.64]}
        rotation={[Math.PI / 2, 0, 1.693]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic.geometry}
        material={materials['atlas_LPUP.019']}
        position={[13.91, 0, 8.8]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic001.geometry}
        material={materials['atlas_LPUP.019']}
        position={[14.308, 0, 9.654]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic002.geometry}
        material={materials['atlas_LPUP.019']}
        position={[15.561, 0, 12.443]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic003.geometry}
        material={materials['atlas_LPUP.019']}
        position={[16.87, 0, 12.955]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic004.geometry}
        material={materials['atlas_LPUP.019']}
        position={[17.496, 0, 12.016]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic005.geometry}
        material={materials['atlas_LPUP.019']}
        position={[18.036, 0, 13.382]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic006.geometry}
        material={materials['atlas_LPUP.019']}
        position={[19.032, 0, 13.979]}
        rotation={[Math.PI / 2, 0, 1.885]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic007.geometry}
        material={materials['atlas_LPUP.019']}
        position={[12.886, 0, 17.394]}
        rotation={[Math.PI / 2, 0, 2.653]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic008.geometry}
        material={materials['atlas_LPUP.019']}
        position={[12.658, 0, 18.191]}
        rotation={[Math.PI / 2, 0, 2.653]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic009.geometry}
        material={materials['atlas_LPUP.019']}
        position={[13.625, 0, 18.39]}
        rotation={[Math.PI / 2, 0, 2.653]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass_basic010.geometry}
        material={materials['atlas_LPUP.019']}
        position={[12.316, 0, 18.988]}
        rotation={[Math.PI / 2, 0, 2.653]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round003.geometry}
        material={materials['atlas_LPUP.020']}
        position={[3.45, -2.33, 12.59]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round004.geometry}
        material={materials['atlas_LPUP.020']}
        position={[3.45, -3.781, -17.063]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round005.geometry}
        material={materials['atlas_LPUP.020']}
        position={[3.45, -3.041, -14.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round006.geometry}
        material={materials['atlas_LPUP.020']}
        position={[3.45, -3.554, 14.497]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_round007.geometry}
        material={materials['atlas_LPUP.020']}
        position={[3.45, -3.411, 10.74]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tile_plain_dirt001.geometry}
        material={materials['atlas_LPUP.021']}
        position={[-4.74, -6.56, 0.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.005, 0.013, 0.01]}
      />
    </group>
  )
}

export default QuizBlockWorld;

useGLTF.preload('/3d-models-quiz/quiz.glb')
